# encoding: utf-8
require 'csv'

 csv = {  
    :Make => "Honda",
    :Doors => 4,
  }

def default_listing
  {
    :Vin => "4N9AL9AP9CC758598",
    :Make=>"Nissan",
    :Model=>"Altima",
    :Trim=>"2.5 S",
    :Year=>"2012",
    :Odometer=>"34740",
    :OdometerUnits=>"m",
    :ExteriorColor=>"Black",
    :InteriorColor=>"Black",
    :StockNumber=>nil,
    :PhysicalLocationInd=>"AU",
    :PhysicalLocationCode=>"RAA",
    :FacilitatedAuctionCode=>"QLM1",
    :TitleStatus=>"Title Present",
    :TitleState=>"GA",
    :EngineCylinders=>"4 Cylinder",
    :Transmission=>"Automatic ",
    :Drivetrain=>"4 Wheel Drive",
    :FuelType=>"Gasoline",
    :AudioType=>"AM/FM/CD",
    :BodyStyle=>"Sedan",
    :TopType=>"Moon Roof",
    :InteriorType=>"Leather",
    :Doors=>nil,
    :AirBagSideCurtain—=>nil,
    :"Air Conditioning—"=>"Y",
    :Airbags—=>nil,
    :"Alloy Wheels—"=>nil,
    :AntilockBrakes—=>nil,
    :ChildSeat—=>nil,
    :ChildSeatAnchors—=>nil,
    :CruiseControl—=>"Y",
    :DualClimateControl—=>nil,
    :DVD—=>nil,
    :GPS=>nil,
    :HeatedSeats—=>nil,
    :PowerBrakes—=>nil,
    :PowerDoorLocks—=>"Y",
    :PowerMirrors—=>nil,
    :PowerSeats—=>nil,
    :PowerSteering—=>"Y",
    :PowerWindows—=>"Y",
    :RearWindowDefroster—=>nil,
    :TiltTeleWheel—=>nil,
    :TintedGlass—=>nil,
    :FrameDamage=>"N",
    :PriorPaint=>"N",
    :PriorPaintDetails=>nil,
    :Salvage=>"N",
    :SoldAsIs=>nil,
    :ConditionReportURL=>nil,
    :ExteriorDamages=>"N",
    :ExtDesc1=>nil,
    :ExtDesc2=>nil,
    :ExtDesc3=>nil,
    :ExtCond1=>nil,
    :ExtCond2=>nil,
    :ExtCond3=>nil,
    :ExtSev1=>nil,
    :ExtSev2=>nil,
    :ExtSev3=>nil,
    :InteriorDamages=>"N",
    :IntDesc1=>nil,
    :IntDesc2=>nil,
    :IntDesc3=>nil,
    :IntCond1=>nil,
    :IntCond2=>nil,
    :IntCond3=>nil,
    :IntSev1=>nil,
    :IntSev2=>nil,
    :IntSev3=>nil,
    :AllTiresMatch=>"Y",
    :LtFrontTireCond=>nil,
    :RtFrontTireCond=>nil,
    :LtRearTireCond=>nil,
    :RtRearTireCond=>nil,
    :SpareTireCond=>nil,
    :Manuals=>nil,
    :Odor=>nil,
    :Keys1=>nil,
    :Keys1Qty=>nil,
    :Keys2=>nil,
    :Keys2Qty=>nil,
    :Keys3=>nil,
    :Keys3Qty=>nil,
    :Comments=>nil,
    :ContactName=>"Mari",
    :CompanyName=>"Manheim",
    :Phone=>"1231231234",
    :Fax=>nil,
    :ListingContactEmail=>"rafael.lima@manheim.com",
    :CCEmail=>"rafael.lima@manheim.com",
    :IMAGEURL1=>"http://i.imgur.com/jgVczie.jpg",
    :IMAGEURL2=>nil,
    :IMAGEURL3=>nil,
    :IMAGEURL4=>nil,
    :IMAGEURL5=>nil,
    :IMAGEURL6=>nil,
    :IMAGEURL7=>nil,
    :IMAGEURL8=>nil,
    :IMAGEURL9=>nil,
    :IMAGEURL10=>nil,
    :AccountGroup=>"ASBURYOPEN",
    :ListingType=>"BUY",
    :StartingBidPrice=>"4000",
    :BidIncrement=>nil,
    :FloorPrice=>nil,
    :BuyNowPrice=>"4000",
    :PreviewStartDate=>nil,
    :StartDate=>"07/23/2013 12:15AM ET",
    :EndDate=>"07/25/2013 12:00AM ET",
    :ListingDuration=>nil,
    :ActionFlag=>nil,
    :ResultsEmail=>"rafael.lima@manheim.com",
    :AllowOffers=>nil,
    :ManheimWorkOrder=>nil,
  }
end

def compare_data(default_listing, user_listing)
  default_listing.merge(user_listing)
end

def import_csv(csv)
  compare_data(default_listing, csv)
end

import_csv(csv)
